#' Parameter Objects
#' 
#' These are objects that can be used for modeling, especially in conjunction
#'  with the \pkg{parsnip} package.  
#' 
#' @return Each object is generated by either `new_quant_param` or 
#' `new_qual_param`. 
#' 
#' @export
#' @rdname parameters
mtry <-
  new_quant_param(
    type = "integer",
    range = c(1L, unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Randomly Selected Predictors"
  )

#' @rdname parameters
#' @export
trees <-
  new_quant_param(
    type = "integer",
    range = c(1L, 2000L),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Trees"
  )

#' @rdname parameters
#' @export
min_n <-
  new_quant_param(
    type = "integer",
    range = c(2L, unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Minimal Node Size"
  )

#' @rdname parameters
#' @export
sample_size <-
  new_quant_param(
    type = "integer",
    range = c(unknown(), unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Observations Sampled"
  )

#' @rdname parameters
#' @export
learn_rate <-
  new_quant_param(
    type = "double",
    range = c(unknown(), unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Learning Rate"
  )


#' @rdname parameters
#' @export
loss_reduction <-
  new_quant_param(
    type = "double",
    range = c(unknown(), unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Minimum Loss Reduction"
  )

#' @rdname parameters
#' @export
tree_depth <-
  new_quant_param(
    type = "integer",
    range = c(2L, 15L),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Tree Depth"
  )


#' @rdname parameters
#' @export
weight_decay <-
  new_quant_param(
    type = "double",
    range = c(-10, 0),
    inclusive = c(TRUE, TRUE),
    trans = log10_trans(),
    label = "L2 Regularization"
  )

#' @rdname parameters
#' @export
dropout <-
  new_quant_param(
    type = "double",
    range = c(0, 1),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Dropout Rate"
  )

#' @rdname parameters
#' @export
epochs <-
  new_quant_param(
    type = "integer",
    range = c(1L, 1000L),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Epochs"
  )

#' @rdname parameters
#' @export
activation <-
  new_qual_param(
    type = "character",
    values = c("linear", "softmax", "relu", "elu"),
    label = "Activation Function"
  )

#' @rdname parameters
#' @export
mixture <- 
  new_quant_param(
    type = "double",
    range = 0:1,
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "% lasso Penalty"
  )

#' @rdname parameters
#' @export
regularization <- 
  new_quant_param(
    type = "double",
    range = c(-10, 0),
    inclusive = c(TRUE, TRUE),
    trans = log10_trans(),
    label = "Amount of Regularization"
  )

# in reference to kknn::kknn
#' @rdname parameters
#' @export
weight_func <-
  new_qual_param(
    type = "character",
    values = c("rectangular", "triangular", "epanechnikov", "biweight", 
               "triweight", "cos", "inv", "gaussian", "rank", "optimal"),
    label = "Distance Weighting Function"
  )

# in reference to survival::survreg
#' @rdname parameters
#' @export
surv_dist <-
  new_qual_param(
    type = "character",
    values = c("weibull", "exponential", "gaussian", "logistic", 
               "lognormal", "loglogistic"),
    label = "Distribution"
  )

#' @export
#' @rdname parameters
prune <-
  new_qual_param(
    type = "logical",
    values = c(TRUE, FALSE),
    label = "Pruning"
  )

#' @export
#' @rdname parameters
rbf_sigma <-
  new_quant_param(
    type = "double",
    range = c(-10, 0),
    inclusive = c(TRUE, TRUE),
    trans = log10_trans(),
    label = "Radial Basis Function sigma"
  )

#' @export
#' @rdname parameters
interact_degree <-
  new_quant_param(
    type = "integer",
    range = 1:2,
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Degree of Interaction"
  )

#' @export
#' @rdname parameters
prod_degree <-
  new_quant_param(
    type = "integer",
    range = 1:2,
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Degree of Interaction"
  )

#' @export
#' @rdname parameters
num_terms <-
  new_quant_param(
    type = "integer",
    range = c(1L, unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Model Terms"
  )

#' @export
#' @rdname parameters
num_comp <-
  new_quant_param(
    type = "integer",
    range = c(1L, unknown()),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Components"
  )

#' @export
#' @rdname parameters
Cp <-
  new_quant_param(
    type = "double",
    range = c(-10, -1),
    inclusive = c(TRUE, TRUE),
    trans = log10_trans(),
    label = "Cost-Complexity Parameter"
  )

#' @export
#' @rdname parameters
cost <-
  new_quant_param(
    type = "double",
    range = c(-10, -1),
    inclusive = c(TRUE, TRUE),
    trans = log2_trans(),
    label = "Cost"
  )

#' @export
#' @rdname parameters
degree <-
  new_quant_param(
    type = "double",
    range = c(1, 3),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Polynomial Degree"
  )

#' @export
#' @rdname parameters
df <-
  new_quant_param(
    type = "double",
    range = c(1, 5),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "Degrees of Freedom"
  )

#' @export
#' @rdname parameters
hidden_units <-
  new_quant_param(
    type = "integer",
    range = c(1L, 10),
    inclusive = c(TRUE, TRUE),
    trans = NULL,
    label = "# Hidden Units"
  )